server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: studentModule
          uri: http://localhost:8081
          predicates:
            - Path=/student/**
        - id: appLogModule
          uri: http://localhost:8082
          predicates:
            - Path=/applog/**
        - id: securityModule
          uri: http://localhost:8084
          predicates:
            - Path=/security/**
#zuul:
#  routes:
#    student-service:
#      path: /student-service/**
#      url: http://localhost:8081/student-service
#    applog-service:
#      path: /applog-service/**
#      url: http://localhost:8082/applog-service
