server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: studentModule
          uri: http://localhost:8081/student-service
          predicates:
            - Path=/student/**
        - id: appLogModule
          uri: http://localhost:8082/applog-service
          predicates:
            - Path=/applog/**